// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MoistureChartController from "./moisture_chart_controller"
application.register("moisture-chart", MoistureChartController)

import TrendChartController from "./trend_chart_controller"
application.register("trend-chart", TrendChartController)
